import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Panel from "@ui5/webcomponents/dist/Panel.js";
declare const _default: Meta<Panel>;
export default _default;
export declare const Basic: UI5StoryArgs<Panel, StoryArgsSlots>;
export declare const Fixed: UI5StoryArgs<Panel, StoryArgsSlots>;
export declare const StickyHeader: UI5StoryArgs<Panel, StoryArgsSlots>;
export declare const CustomHeader: UI5StoryArgs<Panel, StoryArgsSlots>;
