import type { Meta, StoryFn } from "@storybook/web-components";
import type Label from "@ui5/webcomponents/dist/Label.js";
declare const _default: Meta<Label>;
export default _default;
export declare const Template0: StoryFn;
export declare const Template1: StoryFn;
export declare const Template2: StoryFn;
export declare const Template3: StoryFn;
export declare const Template4: StoryFn;
export declare const Template5: StoryFn;
