import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import UploadCollection from "@ui5/webcomponents-fiori/dist/UploadCollection.js";
declare const _default: Meta<UploadCollection>;
export default _default;
export declare const Basic: UI5StoryArgs<UploadCollection, StoryArgsSlots>;
export declare const RenamingFiles: UI5StoryArgs<UploadCollection, StoryArgsSlots>;
export declare const VariousUploadStates: UI5StoryArgs<UploadCollection, StoryArgsSlots>;
export declare const DragAndDrop: UI5StoryArgs<UploadCollection, StoryArgsSlots>;
