import type { Meta, StoryFn } from "@storybook/web-components";
import type Table from "@ui5/webcomponents/dist/Table.js";
declare const _default: Meta<Table>;
export default _default;
export declare const Template0: StoryFn;
export declare const Template1: StoryFn;
export declare const Template2: StoryFn;
export declare const Template3: StoryFn;
export declare const Template4: StoryFn;
export declare const Template5: StoryFn;
export declare const Template6: StoryFn;
export declare const Template7: StoryFn;
export declare const Template8: StoryFn;
