import type { StoryFn, Meta } from "@storybook/web-components";
import type AvatarGroup from "@ui5/webcomponents/dist/AvatarGroup.js";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
declare const _default: Meta<AvatarGroup>;
export default _default;
export declare const Basic: UI5StoryArgs<AvatarGroup, StoryArgsSlots>;
export declare const TypesAndSizes: StoryFn;
export declare const TypeIndividualWithPopover: StoryFn;
export declare const TypeGroupWithPopover: StoryFn;
