# SPDX-FileCopyrightText: SAP SE <https://sap.com>
#
# SPDX-License-Identifier: Apache-2.0

# This file is used for deployment of the playground in master branch on every commit.

url: "https://sap.github.io/ui5-webcomponents/master"
