import type { Meta, StoryFn } from "@storybook/web-components";
import type DatePicker from "@ui5/webcomponents/dist/DatePicker.js";
declare const _default: Meta<DatePicker>;
export default _default;
export declare const Template0: StoryFn;
export declare const Template1: StoryFn;
export declare const Template2: StoryFn;
export declare const Template3: StoryFn;
export declare const Template4: StoryFn;
export declare const Template5: StoryFn;
export declare const Template6: StoryFn;
export declare const Template7: StoryFn;
export declare const Template8: StoryFn;
export declare const Template9: StoryFn;
export declare const Template10: StoryFn;
export declare const Template11: StoryFn;
export declare const Template12: StoryFn;
export declare const Template13: StoryFn;
export declare const Template14: StoryFn;
