import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Badge from "@ui5/webcomponents/dist/Badge.js";
declare const _default: Meta<Badge>;
export default _default;
export declare const Basic: UI5StoryArgs<Badge, StoryArgsSlots>;
export declare const Interactive: UI5StoryArgs<Badge, StoryArgsSlots>;
export declare const WrappingTypes: UI5StoryArgs<Badge, StoryArgsSlots>;
export declare const Designs: UI5StoryArgs<Badge, StoryArgsSlots>;
export declare const Set1: UI5StoryArgs<Badge, StoryArgsSlots>;
export declare const Set2: UI5StoryArgs<Badge, StoryArgsSlots>;
export declare const Set3: UI5StoryArgs<Badge, StoryArgsSlots>;
