import type { Meta, StoryFn } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type ProgressIndicator from "@ui5/webcomponents/dist/ProgressIndicator.js";
declare const _default: Meta<ProgressIndicator>;
export default _default;
export declare const Basic: UI5StoryArgs<ProgressIndicator, StoryArgsSlots>;
export declare const DisplayValue: UI5StoryArgs<ProgressIndicator, StoryArgsSlots>;
export declare const CustomSize: UI5StoryArgs<ProgressIndicator, StoryArgsSlots>;
export declare const ValueStates: StoryFn;
