name: Feature Request
description: Request a new feature or enhancement for this project
title: '[Feature Request]:'
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Request Description
      description: A clear and concise description of what feature is missing.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of the solution you would like to have.
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Proposed Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add other context (f.e business impact), related to the feature request.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 'Priority'
      multiple: false
      options:
        - Low
        - Medium
        - High
        - Very High
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Privacy Policy
      description: By submitting this issue, I confirm to follow the recommendation not to disclose any internal or sensitive information (internal urls, login credentials, screenshots of applications or features in development).
      options:
        - label: I’m not disclosing any internal or sensitive information.
          required: true
