import type { Meta } from "@storybook/web-components";
import type Form from "@ui5/webcomponents/dist/Form.js";
declare const _default: Meta<Form>;
export default _default;
export declare const FormBasic: import("../../../types.js").UI5StoryArgs<Form, import("./argTypes.js").StoryArgsSlots>;
export declare const FormLabelSpan: import("../../../types.js").UI5StoryArgs<Form, import("./argTypes.js").StoryArgsSlots>;
export declare const FormEdit: import("../../../types.js").UI5StoryArgs<Form, import("./argTypes.js").StoryArgsSlots>;
export declare const FormGroup: import("../../../types.js").UI5StoryArgs<Form, import("./argTypes.js").StoryArgsSlots>;
export declare const FormGroupColumnSpan: import("../../../types.js").UI5StoryArgs<Form, import("./argTypes.js").StoryArgsSlots>;
export declare const FormSingleGroup: import("../../../types.js").UI5StoryArgs<Form, import("./argTypes.js").StoryArgsSlots>;
export declare const FormMultipleGroups: import("../../../types.js").UI5StoryArgs<Form, import("./argTypes.js").StoryArgsSlots>;
