import type { Meta } from "@storybook/web-components";
import type Avatar from "@ui5/webcomponents/dist/Avatar.js";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
declare const _default: Meta<Avatar>;
export default _default;
export declare const Basic: UI5StoryArgs<Avatar, StoryArgsSlots>;
export declare const WithImage: UI5StoryArgs<Avatar, StoryArgsSlots>;
export declare const Size: UI5StoryArgs<Avatar, StoryArgsSlots>;
export declare const Styles: UI5StoryArgs<Avatar, StoryArgsSlots>;
