import type AINoticeIndicator from "./AINoticeIndicator.js";
import Button from "@ui5/webcomponents/dist/Button.js";
import Icon from "@ui5/webcomponents/dist/Icon.js";
import Label from "@ui5/webcomponents/dist/Label.js";
import Link from "@ui5/webcomponents/dist/Link.js";
import ResponsivePopover from "@ui5/webcomponents/dist/ResponsivePopover.js";
import Text from "@ui5/webcomponents/dist/Text.js";

export default function AINoticeIndicatorTemplate(this: AINoticeIndicator) {
	return (
		<div>
            <Icon name="ai"/>
			<Link
					id="toggle"
					class="ui5-ai-notice-indicator-toggle"
					accessibleRole="Button"
					onClick={this._handleToggleClick}
				>
					{this._titleText}
					sfsdfdsfd
			</Link>

            <Label class="ui5-ai-notice-indicator-label">
				Verify results before use.
			</Label>

				{this._usePopover &&
					<ResponsivePopover
						open={this._expanded}
						opener="toggle"
						title={this._titleText}
						accessibleNameRef="popover-text"
						contentOnlyOnDesktop={true}
						_hideHeader={true}
						class="ui5-ai-notice-indicator-popover"
						onClose={this._handlePopoverClose}
					>
						<Text id="popover-text">This content was partially or fully generated by artificial intelligence (AI) technologies.
	The Al-generated content may contain inaccuracies due to using multiple information sources. Verify results before use.</Text>
						<div
							slot="footer"
							class="ui5-ai-notice-indicator-footer"
						>
							<Button
								design="Transparent"
								onClick={this._handleCloseButtonClick}
							>
								{this._closeButtonText}
							</Button>
						</div>
					</ResponsivePopover>
				}
		</div>
	);
}
