import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Card from "@ui5/webcomponents/dist/Card.js";
declare const _default: Meta<Card>;
export default _default;
export declare const InteractiveHeader: UI5StoryArgs<Card, StoryArgsSlots>;
export declare const WithList: UI5StoryArgs<Card, StoryArgsSlots>;
export declare const WithTable: UI5StoryArgs<Card, StoryArgsSlots>;
export declare const WithTimeline: UI5StoryArgs<Card, StoryArgsSlots>;
export declare const More: UI5StoryArgs<Card, StoryArgsSlots>;
