import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Calendar from "@ui5/webcomponents/dist/Calendar.js";
declare const _default: Meta<Calendar>;
export default _default;
export declare const Basic: UI5StoryArgs<Calendar, StoryArgsSlots>;
export declare const Bounds: UI5StoryArgs<Calendar, StoryArgsSlots>;
export declare const CalendarTypes: UI5StoryArgs<Calendar, StoryArgsSlots>;
export declare const CalendarWithLegend: UI5StoryArgs<Calendar, StoryArgsSlots>;
