import type { StoryFn, Meta } from "@storybook/web-components";
import type Select from "@ui5/webcomponents/dist/Select.js";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
declare const _default: Meta<Select>;
export default _default;
export declare const Basic: UI5StoryArgs<Select, StoryArgsSlots>;
export declare const ValueStateAndValueStateMessage: StoryFn;
export declare const TwoColumnLayout: StoryFn;
export declare const CustomOptions: StoryFn;
