import type { Meta, StoryFn } from "@storybook/web-components";
import type Input from "@ui5/webcomponents/dist/Input.js";
declare const _default: Meta<Input>;
export default _default;
export declare const Template0: StoryFn;
export declare const Template1: StoryFn;
export declare const Template2: StoryFn;
export declare const Template3: StoryFn;
export declare const Template4: StoryFn;
export declare const Template5: StoryFn;
export declare const Template6: StoryFn;
