import type { Meta } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type Tag from "@ui5/webcomponents/dist/Tag.js";
declare const _default: Meta<Tag>;
export default _default;
export declare const Basic: UI5StoryArgs<Tag, StoryArgsSlots>;
export declare const Interactive: UI5StoryArgs<Tag, StoryArgsSlots>;
export declare const WrappingTypes: UI5StoryArgs<Tag, StoryArgsSlots>;
export declare const Designs: UI5StoryArgs<Tag, StoryArgsSlots>;
export declare const Set1: UI5StoryArgs<Tag, StoryArgsSlots>;
export declare const Set2: UI5StoryArgs<Tag, StoryArgsSlots>;
export declare const Set3: UI5StoryArgs<Tag, StoryArgsSlots>;
