import type { Meta, StoryFn } from "@storybook/web-components";
import type { StoryArgsSlots } from "./argTypes.js";
import type { UI5StoryArgs } from "../../../types.js";
import type ShellBar from "@ui5/webcomponents-fiori/dist/ShellBar.js";
declare const _default: Meta<ShellBar>;
export default _default;
export declare const Basic: UI5StoryArgs<ShellBar, StoryArgsSlots>;
export declare const Search: UI5StoryArgs<ShellBar, StoryArgsSlots>;
export declare const WithJoule: UI5StoryArgs<ShellBar, StoryArgsSlots>;
export declare const Advanced: StoryFn;
