name: Deploy Website [on push]

on:
  push:
    branches: [ new-docs ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.0.1
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install and Build
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        yarn install
        yarn ci:deploy

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: packages/website/build # The folder the action should deploy.
        target-folder: preview
        clean: true