name: Comment on Closing Issue

on:
  issues:
    types: [closed]

jobs:
  comment-on-close:
    runs-on: ubuntu-latest

    steps:
      - name: Comment that the issue can be reopened
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "This issue has been closed. To reopen, just leave a comment!"
            })
