name: Merge Release Changelog

on: workflow_dispatch
  
jobs:
  merge-release-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v4.1.0
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install
      run: yarn --frozen-lockfile

    - name: Merge Release Changelog
      uses: actions/github-script@v7
      env:
          GH_TOKEN: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
      with:
          github-token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
          script: |
            const mergeReleaseChangelog = (await import('${{ github.workspace }}/.github/actions/mergeReleaseChangelog.mjs')).default;

            await mergeReleaseChangelog({ github , context });