name: Release Stable Version

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type: use patch | minor | major or leave empty for auto'     
        required: false
        default: ''
      prerelease:
        type: boolean
        description: 'pre-release'
        required: false
        default: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v4.1.0
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install
      run: yarn --frozen-lockfile

    - name: Version Bump
      env:
        NPM_USERNAME: ${{ secrets.NPM_USER }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
      run: |
        npm config set //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
        git config user.name "${{ secrets.UI5_WEBCOMP_BOT_NAME }}"
        git config user.email "${{ secrets.UI5_WEBCOMP_BOT_EMAIL }}"
        yarn lerna version ${{ github.event.inputs.release_type }}\
            ${{ (github.event.inputs.prerelease == 'true' && '--conventional-prerelease --force-publish') || '--conventional-graduate --force-conventional-graduate' }} \
            --yes --exact --create-release github

    - name: Build
      run: yarn ci:releasebuild

    - name: Publish
      env:
        NPM_USERNAME: ${{ secrets.NPM_USER }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
      run: yarn lerna publish from-git --yes

    - name: Publish Release Comments
      uses: actions/github-script@v7
      env:
          NODE_OPTIONS: '--max-old-space-size=12096'
          GH_TOKEN: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
      with:
          github-token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
          script: |
            const commentOnFixedIssues = (await import('${{ github.workspace }}/.github/actions/commentOnFixedIssues.mjs')).default;

            await commentOnFixedIssues({ github, context });

    - name: Merge Release Changelog
      uses: actions/github-script@v7
      env:
          GH_TOKEN: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
      with:
          github-token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
          script: |
            const mergeReleaseChangelog = (await import('${{ github.workspace }}/.github/actions/mergeReleaseChangelog.mjs')).default;

            await mergeReleaseChangelog({ github , context });
