name: Release on tag

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Set env
      run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Install
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Get Branch
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        BRANCH=${raw/origin\/}
        echo BRANCH: $BRANCH
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

    - name: Publish
      env:
        NPM_USERNAME: ${{ secrets.NPM_USER }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
      run: |
        echo ${{ env.BRANCH }}
        echo ${{ env.VERSION }}
        npm config set //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
        git config user.name "${{ secrets.UI5_WEBCOMP_BOT_NAME }}"
        git config user.email "${{ secrets.UI5_WEBCOMP_BOT_EMAIL }}"
