name: Release on tag

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Set env
      run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV'

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Get Branch
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        BRANCH=${raw/origin\/}
        echo BRANCH: $BRANCH
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

    - name: Publish
      env:
        NPM_USERNAME: ${{ secrets.NPM_USER }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo ${{ env.BRANCH }}
        npm config set //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        git checkout ${{ env.BRANCH }}
        yarn lerna version ${{ env.VERSION }} --conventional-commits --force-git-tag --yes --create-release github 
        yarn lerna publish from-git --yes
