name: Reset Github Pages

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn ci:releasebuild

    - name: Publish
      env:
        NPM_USERNAME: ${{ secrets.NPM_USER }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
      run: |
        git config user.name "${{ secrets.UI5_WEBCOMP_BOT_NAME }}"
        git config user.email "${{ secrets.UI5_WEBCOMP_BOT_EMAIL }}"
        git checkout gh-pages
        git checkout -f 
        git add -A
        git commit -am "reset history"
        git branch -D gh-pages
        git branch -m gh-pages
        git push -f origin gh-pages
