name: Test Fiori

on:
  pull_request:
  push:
    branches:
      - githhub-actions
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn

    - name: Build
      run: ENABLE_CLDR=1 yarn build

    - name: Test
      run: yarn test:fiori
